#!/bin/sh
mkdir -p /usr/share/rpikernelhack/overlays
mkdir -p /boot/overlays
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/bcm2708-rpi-b-plus.dtb /boot/bcm2708-rpi-b-plus.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/bcm2708-rpi-b.dtb /boot/bcm2708-rpi-b.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/bcm2708-rpi-cm.dtb /boot/bcm2708-rpi-cm.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/bcm2709-rpi-2-b.dtb /boot/bcm2709-rpi-2-b.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/bcm2710-rpi-3-b.dtb /boot/bcm2710-rpi-3-b.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/kernel.img /boot/kernel.img
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/kernel7.img /boot/kernel7.img
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/COPYING.linux /boot/COPYING.linux
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/README /boot/overlays/README
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/ads7846-overlay.dtb /boot/overlays/ads7846-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/at86rf233-overlay.dtb /boot/overlays/at86rf233-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/bmp085_i2c-sensor-overlay.dtb /boot/overlays/bmp085_i2c-sensor-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/dht11-overlay.dtb /boot/overlays/dht11-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/enc28j60-overlay.dtb /boot/overlays/enc28j60-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/gpio-ir-overlay.dtb /boot/overlays/gpio-ir-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/gpio-poweroff-overlay.dtb /boot/overlays/gpio-poweroff-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hifiberry-amp-overlay.dtb /boot/overlays/hifiberry-amp-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hifiberry-dac-overlay.dtb /boot/overlays/hifiberry-dac-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hifiberry-dacplus-overlay.dtb /boot/overlays/hifiberry-dacplus-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hifiberry-digi-overlay.dtb /boot/overlays/hifiberry-digi-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hy28a-overlay.dtb /boot/overlays/hy28a-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/hy28b-overlay.dtb /boot/overlays/hy28b-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/i2c-gpio-overlay.dtb /boot/overlays/i2c-gpio-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/i2c-rtc-overlay.dtb /boot/overlays/i2c-rtc-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/i2c0-bcm2708-overlay.dtb /boot/overlays/i2c0-bcm2708-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/i2c1-bcm2708-overlay.dtb /boot/overlays/i2c1-bcm2708-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/i2s-mmap-overlay.dtb /boot/overlays/i2s-mmap-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/iqaudio-dac-overlay.dtb /boot/overlays/iqaudio-dac-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/iqaudio-dacplus-overlay.dtb /boot/overlays/iqaudio-dacplus-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/lirc-rpi-overlay.dtb /boot/overlays/lirc-rpi-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/mcp2515-can0-overlay.dtb /boot/overlays/mcp2515-can0-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/mcp2515-can1-overlay.dtb /boot/overlays/mcp2515-can1-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/mmc-overlay.dtb /boot/overlays/mmc-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/mz61581-overlay.dtb /boot/overlays/mz61581-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pi3-act-led-overlay.dtb /boot/overlays/pi3-act-led-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pi3-disable-bt-overlay.dtb /boot/overlays/pi3-disable-bt-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pi3-miniuart-bt-overlay.dtb /boot/overlays/pi3-miniuart-bt-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/piscreen-overlay.dtb /boot/overlays/piscreen-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/piscreen2r-overlay.dtb /boot/overlays/piscreen2r-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pitft28-capacitive-overlay.dtb /boot/overlays/pitft28-capacitive-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pitft28-resistive-overlay.dtb /boot/overlays/pitft28-resistive-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pps-gpio-overlay.dtb /boot/overlays/pps-gpio-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pwm-2chan-overlay.dtb /boot/overlays/pwm-2chan-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/pwm-overlay.dtb /boot/overlays/pwm-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/qca7000-overlay.dtb /boot/overlays/qca7000-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/raspidac3-overlay.dtb /boot/overlays/raspidac3-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-backlight-overlay.dtb /boot/overlays/rpi-backlight-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-dac-overlay.dtb /boot/overlays/rpi-dac-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-display-overlay.dtb /boot/overlays/rpi-display-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-ft5406-overlay.dtb /boot/overlays/rpi-ft5406-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-proto-overlay.dtb /boot/overlays/rpi-proto-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/rpi-sense-overlay.dtb /boot/overlays/rpi-sense-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/sdhost-overlay.dtb /boot/overlays/sdhost-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/sdio-overlay.dtb /boot/overlays/sdio-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/smi-dev-overlay.dtb /boot/overlays/smi-dev-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/smi-nand-overlay.dtb /boot/overlays/smi-nand-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/smi-overlay.dtb /boot/overlays/smi-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/spi-bcm2708-overlay.dtb /boot/overlays/spi-bcm2708-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/spi-bcm2835-overlay.dtb /boot/overlays/spi-bcm2835-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/spi-dma-overlay.dtb /boot/overlays/spi-dma-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/tinylcd35-overlay.dtb /boot/overlays/tinylcd35-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/uart1-overlay.dtb /boot/overlays/uart1-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/vc4-kms-v3d-overlay.dtb /boot/overlays/vc4-kms-v3d-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/vga666-overlay.dtb /boot/overlays/vga666-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/w1-gpio-overlay.dtb /boot/overlays/w1-gpio-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/w1-gpio-pullup-overlay.dtb /boot/overlays/w1-gpio-pullup-overlay.dtb
dpkg-divert --package rpikernelhack --divert /usr/share/rpikernelhack/overlays/wittypi-overlay.dtb /boot/overlays/wittypi-overlay.dtb
export INITRD=No
if [ -d "/etc/kernel/preinst.d" ]; then
  run-parts -v --report --exit-on-error --arg=4.1.20+ --arg=/boot/kernel.img /etc/kernel/preinst.d
  run-parts -v --report --exit-on-error --arg=4.1.20-v7+ --arg=/boot/kernel7.img /etc/kernel/preinst.d
fi
if [ -d "/etc/kernel/preinst.d/4.1.20+" ]; then
  run-parts -v --report --exit-on-error --arg=4.1.20+ --arg=/boot/kernel.img /etc/kernel/preinst.d/4.1.20+
fi
if [ -d "/etc/kernel/preinst.d/4.1.20-v7+" ]; then
  run-parts -v --report --exit-on-error --arg=4.1.20-v7+ --arg=/boot/kernel7.img /etc/kernel/preinst.d/4.1.20-v7+
fi
#DEBHELPER#
